# -*- coding: utf-8 -*-
"""House Price Predication - USA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BOmfkvEKbWJ3O9wJ0jFlxaHxQ4IoxHbG
"""

from google.colab import drive
drive.mount('/content/drive')

"""1- Import all Necessary Libraries

Mounting Google Drive
"""

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

"""2. Importing the data

"""

df = pd.read_csv('/content/drive/MyDrive/USA House Price Prediction Project/USA_Housing.csv')

"""3. Data Overview"""

df.head(10)

df = df.drop(['Address'],axis=1)
df.head()

df.describe()

df.info

df.isna().sum()

"""Exploratory Data Analysis"""

fig,axes = plt.subplots(nrows=1,ncols=5,figsize=(16,6))

axes[0].plot(df['Avg. Area Income'],df['Price'],'o')
axes[0].set_ylabel("Price")
axes[0].set_title("Avg. Area Income")

axes[1].plot(df['Avg. Area House Age'],df['Price'],'o')
axes[1].set_title("Avg. Area House Age")
axes[1].set_ylabel("Price")

axes[2].plot(df['Avg. Area Number of Rooms'],df['Price'],'o')
axes[2].set_title("Avg. Area Number of Rooms");
axes[2].set_ylabel("Price")

axes[3].plot(df['Avg. Area Number of Bedrooms'],df['Price'],'o')
axes[3].set_title("Avg. Area Number of Bedrooms");
axes[3].set_ylabel("Price")

axes[4].plot(df['Area Population'],df['Price'],'o')
axes[4].set_title("Area Population");
axes[4].set_ylabel("Price")
plt.tight_layout();

sns.pairplot(df)

sns.distplot(df['Price'])

sns.heatmap(df.corr(), annot=True, cmap='Reds')

"""5- Determine the Features & Target Variable"""

df.columns

x=df[['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms',
       'Avg. Area Number of Bedrooms', 'Area Population']]

y=df['Price']

y

"""
6- Split the Dataset to Train & Test
"""

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=101)

"""7- Train the Model"""

from sklearn.linear_model import LinearRegression

model= LinearRegression()

model.fit(x_train, y_train)

LinearRegression()

"""With the coefficient; if one unit increases, the value will increase by the coefficient value

"""

pd.DataFrame(model.coef_, x.columns, columns=['coef'])

"""8- Predicting Test Data"""

predictions=model.predict(x_test)

plt.scatter(y_test, predictions)

"""** 9- Evaluating the Model **

"""

from sklearn import metrics

print('MAE:', metrics.mean_absolute_error(y_test,predictions))
print('MSE:', metrics.mean_squared_error(y_test,predictions))
print('RSME:', np.sqrt(metrics.mean_squared_error(y_test,predictions)))

df['Price'].mean()

"""** 10-Residuals **"""

sns.displot(y_test-predictions)

sns.scatterplot(x=y_test, y=y_test-predictions)
plt.axhline(y=0, color='r', ls='--')



import scipy as sp
# Create a figure and axis to plot on
fig, ax = plt.subplots(figsize=(6,6))
# probplot returns the raw values if needed
# we just want to see the plot, so we assign these values to _
_ = sp.stats.probplot(y_test-predictions,plot=ax)